### ISSUE TITLE
Make issue template

### ISSUE THREAD

**Issue by Foxboron** [Foxboron/sbctl#117]
Issues should demand people attach the following outputs:

* `sudo sbctl status`
* `sudo hexdump -C /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c`

And we should preferably implement `sudo sbctl debug` as a hidden command so we can have some better structured data we can use for debugging.

**Comment by Foxboron** [comment]
@AkechiShiro If you want to want to work on this please do :)

Make an issue template as described by github; https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by AkechiShiro** [comment]
So having a look at the documentation, I think this is a good start point, but I'm sure you will have more relevant feedback onto what should be added or removed for bug reports, as I've never dealt with any bugs/issue so far, for this project.

```yaml
name: Bug Report
description: File a bug report
title: "[Bug]:"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
```
