### ISSUE TITLE
enroll-keys --microsoft seems to enroll more microsoft keys than necessary for Option ROM

### ISSUE THREAD

**Issue by Ten0** [Foxboron/sbctl#361]
Hello,

I'm currently setting up secure boot using this tool, and the process was really simple, thanks!
It worked fine, and I have "Secure Boot" enabled - however it looks like I have too many allowed keys:
- I do not want it to be possible to e.g. reinstall windows or boot windows installation media or other Ubuntu-signed stuff without clearing the keys
- Following the recommendations at https://github.com/Foxboron/sbctl/wiki/FAQ#option-rom I have used the `--microsoft` option to try and enroll the `Microsoft Corporation UEFI CA 2011`, to avoid bricking my device.
- According to my BIOS, there is a key exchange key by microsoft that was also enrolled. My understanding is that this allows new keys signed by Microsoft to be enrolled directly without requiring the KEK that was generated by this tool. I'm not sure what this is useful for in my scenario.
- According to my BIOS again, the DB Signature list contains not only `Microsoft Corporation UEFI CA 2011`, but also `Microsoft Windows Production PCA 2011`, which IIUC allows booting windows and windows installation media. I'm not sure what this is useful for in my scenario.
- `sbctl list-enrolled-keys` seems to confirm this:
  ```
  PK:
    Platform Key
  KEK:
    Key Exchange Key
    Microsoft Corporation Third Party Marketplace Root
  DB:
    Database Key
    Microsoft Corporation Third Party Marketplace Root
    Microsoft Root Certificate Authority 2010
  ```

- Revocations database (`DBX`) was emptied by the "clear/re-enroll keys" process, which unless I'm mistaken allows secure boot bypass using the leaked keys.

Can you please expand on:
1. How to also register revocations when enrolling Microsoft keys, to avoid secure boot bypass?
2. Whether it is really only necessary to enroll the `Microsoft Corporation UEFI CA 2011` but not the other Windows keys to avoid potentially bricking the device and if that is indeed the case, how to achieve that?

Thanks,

NB: According to `tpm2_eventlog` which does not yield `BOOT_SERVICES_DRIVER` lines, it seems that I may not have the need to enroll Microsoft keys on my device.
However I have other lines that look very similar, with a bunch of hashes:
```
- EventNum: 1
  PCRIndex: 0
  EventType: EV_S_CRTM_VERSION
  DigestCount: 2
  Digests:
  - AlgorithmId: sha1
    Digest: "ad55cbf903d61eabfefd923453101e0ba8421486"
  - AlgorithmId: sha256
    Digest: "c68d16dff1c930126030e8ed626ccb4b011e60d767845a965e59523c059ed848"
  EventSize: 12
  Event: "31002e0036002e0030000000"
- EventNum: 2
  PCRIndex: 0
  EventType: EV_EFI_PLATFORM_FIRMWARE_BLOB
  DigestCount: 2
  Digests:
  - AlgorithmId: sha1
    Digest: "6cbc65cab32875d853ed9a53f7c1004b9cde42bb"
  - AlgorithmId: sha256
    Digest: "e2e08958243a14472c7837d0cf5a69bee5bfd1c4845c159d40eefa0338d1d204"
  EventSize: 16
  Event:
    BlobBase: 0x9a00000
    BlobLength: 0x400000
```
Is it absolutely guaranteed that I can not enroll the Microsoft keys and I'll still be able to access BIOS? (I wouldn't really want to brick my device ^^)

Thanks in advance,
