### ISSUE TITLE
Feature request: MOK & Shim support

### ISSUE THREAD

**Issue by Jaakkonen** [Foxboron/sbctl#85]
On some machines enabling UEFI secure boot setup mode is a no-can-do due to company policies or horrible UEFI UIs.
Support for using a Microsoft CA signed Shim with a MOK key would enable using secure boot on these machines.

**Comment by Foxboron** [comment]
I don't personally have any use for MOK+shim. `mokutils` seems fairly usable and I don't see what is missing from a usability standpoint?

The Microsoft CA stuff is going to be unconditionally added unless opted out in the future.

**Comment by EvilBit** [comment]
> The Microsoft CA stuff is going to be unconditionally added unless opted out in the future.

You mean `sbctl enroll-keys` will automatically add Microsoft's keys in the future?

**Please make it opt-in rather than opt-out.**

Adding back Microsoft's keys is most likely **not** the majority use case, and making a SB setup less secure by signing 3rd party keys should be a user's active decision, i.e. *opt-in*.
After all, why add back Microsoft's keys when going through the trouble of rolling your own SB PK setup? Kind of defeats the primary purpose of having full control over your chain of trust. ;)

**Comment by Foxboron** [comment]
>Please make it opt-in rather than opt-out.

Can't do that. We don't know if there is any signed oprom in the boot process and if we enroll custom signing keys without having this in the clear the computer simply wont POST. This is just going to brick peoples laptops for no good reasons.

>Adding back Microsoft's keys is most likely not the majority use case, and making a SB setup less secure by signing 3rd party keys should be a user's active decision, i.e. opt-in.

It is, which is the issue. UEFI Class 3+ which is what Intel is targeting from 2021 and onwards, along with Windows 11 demanding TPM+SecureBoot support we'll most likely see more signed oprom we can't discover in boot process. Especially outside of the laptop market.

The goal here is to be user-friendly, so the only sane thing here is to make it opt-out with a warning for people that know what they are doing. Anything else is going to have people come to us (read "me") and complain about broken computers. Don't want to deal with that.

>Kind of defeats the primary purpose of having full control over your chain of trust. ;)

I have ranted to UEFI WG people. There is nothing we can do here.

**Comment by Foxboron** [comment]
>You mean sbctl enroll-keys will automatically add Microsoft's keys in the future?

I'm probably going to abstract away `create-keys` and `enroll-keys` into a `setup` command which is going to be a bit more user-friendly for the initial setup. I don't think the low-level plumbing commands is going to change in this regard.

**Comment by Foxboron** [comment]
>You mean sbctl enroll-keys will automatically add Microsoft's keys in the future?

I'm probably going to abstract away `create-keys` and `enroll-keys` into a `setup` command which is going to be a bit more user-friendly for the initial setup. I don't think the low-level plumbing commands is going to change in this regard.

**Comment by EvilBit** [comment]
> It is, which is the issue. UEFI Class 3+ which is what Intel is targeting from 2021 and onwards, along with Windows 11 demanding TPM+SecureBoot support we'll most likely see more signed oprom we can't discover in boot process. Especially outside of the laptop market.

Damn, didn't think about OPROMs - those pesky things keep coming back to haunt us. Already a source of severe exploits in the past (see e.g. [Thunderstrike](https://trmm.net/Thunderstrike/)).
AFAIK they are also only necessary if you rely on devices which need OPROMs during BDS stage in UEFI and afterwards unnecessary for booting an OS with sane device driver initialization, à la linux.
Actually, I'm trying to get rid of all the DXE stage onwards UEFI madness right now with LinuxBoot / NERF firmware - I'm curious how that will work together with secure boot and `sbctl`.

> The goal here is to be user-friendly, so the only sane thing here is to make it opt-out with a warning for people that know what they are doing. Anything else is going to have people come to us (read "me") and complain about broken computers. Don't want to deal with that.

Yeah, I understand that concern of course.
I propose to make it not only a warning, but a mandatory flag, e.g. `--include-microsoft-keys` or `--include-vendor-keys`, without which enrolling errors out with an explanation. Additionally an `--expert` flag which silences those kinds of safety checks.

**Comment by WhyNotHugo** [comment]
Isn't signing the oproms with the new keys also a possibility?

Adding MS's keys kinda defeats the purpose of using SecureBoot completely: the system will only run code signed with a private key, but they key is in the hand of a completely untrustworthy third party that's signed software for uncountable others too.

There's also the possibility of **no** default, and prompting the user to pick. But adding a third party's key is a huge security issue   that really shouldn't be the default. I'd kinda akin to setting the root password a pre-defined default value; even if it's not public, it's very far from being safe.

**Comment by Foxboron** [comment]
>Isn't signing the oproms with the new keys also a possibility?

Then you need to start hardware hacking. Oprom extraction, modify it and write it back. It's not something that can be done from userspace.

https://github.com/osresearch/safeboot/issues/84#issuecomment-815402662

>There's also the possibility of no default, and prompting the user to pick. But adding a third party's key is a huge security issue that really shouldn't be the default. 

There isn't really any good way around this. I wish it would be easier to detect signed oprom from userspace but I don't think it's possible.

**Comment by WhyNotHugo** [comment]
Oh, shit. Sounds like UEFI SecureBoot wasn't really though out 100%, and they shipped it quickly without really considering it being actually used.

**Comment by EvilBit** [comment]
Well, to be fair, I've yet to personally stumble over a (signed) Option ROM that's _actually_ necessary for booting modern hardware (even in server hardware space). That doesn't mean they don't exist and might change with UEFI Class 3+.
I believe Trammell Hudson (@osresearch) did more in-depth research on disabling as many untrusted Option ROMs as possible and came to a similar conclusion (?).

In practice, one should probably strive to replace the whole DXE & Option ROM phase with something like LinuxBoot, NERF, coreboot (if lucky enough with hardware), etc.

---
To reiterate, I believe forcing the user to make an active choice via two mutually exclusive command line flags would be best, à la `--include-microsoft-keys` vs. `--no-include-microsoft-keys` (maybe `vendor` instead of `microsoft`). Without any of the two present, the programm would error out with an explanatory message.

That way, we wouldn't establish in an insecure default, protecting users from both:
* inadvertently backdooring their computer via an untrustworthy root of trust
* carelessly locking themselves out of their computer via missing cert chain

**Comment by osresearch** [comment]
I haven't encountered any laptops that require option roms (most of my research is on Thinkpads and NUCs), although servers and desktops definitely use them, especially if the system has an external GPU for primary video or RAID card for booting.  One of the safeboot contributors hit this  with their desktop and had to track down a VGA monitor to be able to use the on-board video to reset the UEFI `PK`.

Re-signing the option rom as described in https://github.com/osresearch/safeboot/issues/84#issuecomment-815402662 is probably unnecessary (and fraught with peril if things go wrong or if the firmware is reset to factory keys) -- the hash of the existing ROM can be added to the `db`, right?  This would also eliminate a roll-back attacks where an adversary installs an older vulnerable version of an option ROM.

The option ROMs *should* show up in the tpm event log, so it *should* be possible to parse that to find any that were loaded during boot and perhaps offer to sign them with the user provided `PK` or `KEK` so they can be enrolled in the `db`.

**Comment by Foxboron** [comment]
>the hash of the existing ROM can be added to the db, right? This would also eliminate a roll-back attacks where an adversary installs an older vulnerable version of an option ROM.

The issue I see is that we need the Authenticode checksum of the OpROM. I don't how we can realistically retrieve this file from Linux userspace? The comment from safeboot implies it can be extracted but this is out-of-scope for any user friendly tooling.

The TPM eventlog is also going to record the checksum of the file itself, so if we can find the checksum in the eventlog we still can't enroll it into the `db`.

>The option ROMs should show up in the tpm event log, so it should be possible to parse that to find any that were loaded during boot and perhaps offer to sign them with the user provided PK or KEK so they can be enrolled in the db.

I'm not clear how we can sign this file from Linux userspace though.

**Comment by Foxboron** [comment]
Wait, I forget if we need the authenticode checksum or a standard sha256sum of the file for the `db` and `dbx` variable?

**Comment by Foxboron** [comment]
Ah, it's the checksum of the oprom itself!

UEFI spec 2.8 errata A, February 2020.
Page 1727, Table 227. "Authorization process flow", 2 A.

But then I need to figure out how we can properly parse the eventlog for loaded oprom. I wonder how easy it would be to obtain an example log with that? @orangecms do you have an idea :)?

**Comment by osresearch** [comment]
It's a little odd that they don't use the authenticode, but my guess is that this allows easier compatibility with legacy unsigned ROMs that need to be added to the allow-list.  For things that are signed, the eventlog contains the authenticode hash, such as `EV_EFI_BOOT_SERVICES_APPLICATION` when loading `shimx64.efi`:

```
- EventNum: 24
  PCRIndex: 4
  EventType: EV_EFI_BOOT_SERVICES_APPLICATION
  DigestCount: 2
  Digests:
  - AlgorithmId: sha1
    Digest: "21e79438580ec89df674dfe12653d77d132c3936"
  - AlgorithmId: sha256
    Digest: "2ea4cb6a1f1eb1d3dce82d54fde26ded243ba3e18de7c6d211902a594fe56788"
  EventSize: 170
  Event:
    ImageLocationInMemory: 0x75943018
    ImageLengthInMemory: 1341560
    ImageLinkTimeAddress: 0x0
    LengthOfDevicePath: 138
    DevicePath: '02010c00d041030a0000000001010600001d01010600000003171000010000000025385b0142db5204012a000100000000080000000000000000100000000000904af79b23573d4abc468a6548cbb75e0202040434005c004500460049005c007500620075006e00740075005c007300680069006d007800360034002e0065006600690000007fff0400'
```

verified with:
```
# sbsign.safeboot --hash-only /boot/efi/EFI/ubuntu/shimx64.efi
warning: data remaining[1177936 vs 1341560]: gaps between PE/COFF sections?
2ea4cb6a1f1eb1d3dce82d54fde26ded243ba3e18de7c6d211902a594fe56788
```

I'll see if I can track down an eventlog with an option rom in it since most of my systems don't have them.

**Comment by Foxboron** [comment]
If we can get by with just reading the eventlog for oprom and stuffing the checksum into `db` it would make things a lot simpler.

It would be interesting if i could try boot a qemu instance some placeholder oprom with an emulated tpm? Not sure how possible that would be.

**Comment by osresearch** [comment]
qemu with ovmf and ipxe has these entries in the eventlog.  The `BOOT_SERVICES_APPLICATION` is my kernel, although the `EV_EFI_BOOT_SERVICES_DRIVER` should be the ipxe, but doesn't match any of the files in `/usr/lib/ipxe/qemu/*.rom` so I'm trying to figure out where that hash comes from.

```
- EventNum: 1
  PCRIndex: 0
  EventType: EV_S_CRTM_VERSION
  DigestCount: 2
  Digests:
  - AlgorithmId: sha1
    Digest: "1489f923c4dca729178b3e3233458550d8dddf29"
  - AlgorithmId: sha256
    Digest: "96a296d224f285c67bee93c30f8a309157f0daa35dc5b87e410b78630a09cfc7"
  EventSize: 2
  Event: "0000"
- EventNum: 2
  PCRIndex: 0
  EventType: EV_EFI_PLATFORM_FIRMWARE_BLOB
  DigestCount: 2
  Digests:
  - AlgorithmId: sha1
    Digest: "3f32b9a5c407bccf010934da6b80dda4cd160bb5"
  - AlgorithmId: sha256
    Digest: "a6dfbab05de8afdef2eb5e075b56f277fff9cd752d40f1a2360ea0e082159666"
  EventSize: 16
  Event:
    BlobBase: 0x820000
    BlobLength: 0xe0000
- EventNum: 3
  PCRIndex: 0
  EventType: EV_EFI_PLATFORM_FIRMWARE_BLOB
  DigestCount: 2
  Digests:
  - AlgorithmId: sha1
    Digest: "5178d24da0e0124f8100089f24725eb0ca865cca"
  - AlgorithmId: sha256
    Digest: "362cc6af7cc330ab3c10696edec503fc4341524711c31a509f2c9c2204365436"
  EventSize: 16
  Event:
    BlobBase: 0x900000
    BlobLength: 0xb00000
....
- EventNum: 10
  PCRIndex: 2
  EventType: EV_EFI_BOOT_SERVICES_DRIVER
  DigestCount: 2
  Digests:
  - AlgorithmId: sha1
    Digest: "3cab2aa673fc6a7f6e1765a82c04be90b110507f"
  - AlgorithmId: sha256
    Digest: "58c91e43a3a34c0784008712501dbfa44841ff67e6ec0db178d929bd40d3958f"
  EventSize: 78
  Event:
    ImageLocationInMemory: 0x3f207018
    ImageLengthInMemory: 216520
    ImageLinkTimeAddress: 0x0
    LengthOfDevicePath: 46
    DevicePath: '02010c00d041030a0000000001010600000204081800000000000064010000000000ffb10400000000007fff0400'
...
- EventNum: 27
  PCRIndex: 4
  EventType: EV_EFI_BOOT_SERVICES_APPLICATION
  DigestCount: 2
  Digests:
  - AlgorithmId: sha1
    Digest: "42ee27c5f05ba7b377905f1d54611f214b4b8185"
  - AlgorithmId: sha256
    Digest: "ec1899aefaad2092e8f736ebd1964f23089fb1ca73f0f873e9304dc071843c91"
  EventSize: 118
  Event:
    ImageLocationInMemory: 0x3d11e018
    ImageLengthInMemory: 19242912
    ImageLinkTimeAddress: 0x0
    LengthOfDevicePath: 86
    DevicePath: '02010c00d041030a00000000010106000002030b2500525400123456000000000000000000000000000000000000000000000000000001030c1b0000000000000000000000000000000000000000000000007fff0400'

```
